# Setup build directories

SET(BUILD_DIRECTORY_SETUP YES)

MESSAGE(STATUS "Setup build directories.")

IF("${CMAKE_BUILD_TYPE}" STREQUAL "")
SET(CMAKE_BUILD_TYPE "Debug")
ENDIF("${CMAKE_BUILD_TYPE}" STREQUAL "")
MESSAGE(STATUS "Build mode is ${CMAKE_BUILD_TYPE}")

# force output into several folders
SET (CMAKE_LIBRARY_OUTPUT_DIRECTORY
     ${PROJECT_BINARY_DIR}/bin/${CMAKE_BUILD_TYPE} )
SET (CMAKE_RUNTIME_OUTPUT_DIRECTORY
     ${PROJECT_BINARY_DIR}/bin/${CMAKE_BUILD_TYPE} )
SET (CMAKE_ARCHIVE_OUTPUT_DIRECTORY
     ${PROJECT_BINARY_DIR}/bin/${CMAKE_BUILD_TYPE} )
SET(CMAKE_PROJECT_DOC_DIR
    ${PROJECT_BINARY_DIR}/doc )
SET(CMAKE_CURRENT_BINARY_DIR
    ${PROJECT_BINARY_DIR}/moc  )

# Make directory for tests
FILE(MAKE_DIRECTORY ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/test)

