### CPack Convenience Macro

MACRO(setup_cpack)

  SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "${CPACK_PACKAGE_VENDOR} <m@cr8tr.org>") #required 

  SET(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
  SET(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
  SET(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)

  SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "OMNIDOME is a arbitrary surface projection mapping tool built by CR8TR. It allows you to map any physical room and project virtual content back on to it.")

  #if ((${MAJOR_VERSION} EQUAL 0 AND (${MINOR_VERSION} EQUAL 0) AND (${PATCH_VERSION} EQUAL 0))
  #  MESSAGE(WARNING "Version number is not valid (you are not on a version branch). CPack will not be executed.")
  #  return()
  #endif (${MAJOR_VERSION} EQUAL 0 AND (${MINOR_VERSION} EQUAL 0) AND (${PATCH_VERSION} EQUAL 0))
  set(CPACK_PACKAGE_NAME ${CMAKE_PROJECT_NAME})
  set(CPACK_PACKAGE_VENDOR "cr8tr")
  set(CPACK_PACKAGE_VERSION "${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}")
  set(CPACK_PACKAGE_VERSION_MAJOR "${MAJOR_VERSION}")
  set(CPACK_PACKAGE_VERSION_MINOR "${MINOR_VERSION}")
  set(CPACK_PACKAGE_VERSION_PATCH "${PATCH_VERSION}")

  IF(${CMAKE_SYSTEM_NAME} MATCHES "Darwin") # If mac os x
    set(CPACK_BINARY_DRAGNDROP ON)
    set(CPACK_DMG_VOLUME_NAME ${CMAKE_PROJECT_NAME})
  ELSE()
    SET(CPACK_GENERATOR "DEB")
  ENDIF()

  include(CPack)
ENDMACRO(setup_cpack)
