
set( MAJOR_VERSION 1 )
set( MINOR_VERSION 0 )
set( PATCH_VERSION 0 )
set( VERSION_STRING "${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}")
add_definitions(-DOMNIDOME_VERSION_STRING=${VERSION_STRING}
  -DOMNIDOME_MAJOR_VERSION="${MAJOR_VERSION}"
  -DOMNIDOME_MINOR_VERSION="${MINOR_VERSION}"
  -DOMNIDOME_PATCH_VERSION="${PATCH_VERSION}"
)
